import { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";
import { Inter } from "next/font/google"; // Import the Inter font
import { CartProvider } from "@/context/CartContext";
import { LanguageProvider } from "@/context/LanguageContext";
import Footer from "@/components/shared/Footer";

// Initialize the Inter font with desired subsets and weights
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Specify weights you need
  variable: "--font-inter", // Optional: CSS variable for custom usage
});

const absoluteUrl = "/logo/logo.svg";

export const metadata: Metadata = {
  title: "Georgia travel",
  description: "Generated by create next app",
  openGraph: {
    title: "Georgia travel",
    description: "Generated by create next app",
    url: absoluteUrl,
    siteName: "Georgia Travel Site",
    images: [
      {
        url: `${absoluteUrl}`,
        width: 800,
        height: 600,
        alt: "Georgia travel logo",
      },
    ],
    locale: "ka_GE",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Georgia travel",
    description: "Generated by create next app",
    images: [`${absoluteUrl}`],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="icon" href="/logo/logo.svg" sizes="any" />
      </head>
      <body>
        <LanguageProvider>
          <CartProvider>
            <Header />
            <main className="min-h-screen">{children}</main>
          </CartProvider>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
